CREATE TABLE user_login (
  id BIGSERIAL NOT NULL,
  login VARCHAR(255) NOT NULL ,
  token VARCHAR(2048),
  tokens_used BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  PRIMARY KEY(id)
);